name: CI/CD - SonarCloud e Deploy GCP

on:
  push:
    branches:
      - code
  pull_request:
    branches:
      - code

jobs:
  deploy_to_gcp:
    name: Deploy GCP
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate Google Cloud CLI
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }} 

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: pip install -r fleettrack/requirements.txt
      
    - name: Collect Static Files
      run: python fleettrack/manage.py collectstatic --noinput
      env:
          PYTHONPATH: .
    - name: Debug - List files
      run: |
        echo "Current working directory:"
        pwd
        echo "List all files recursively:"
        ls -R

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v2
      with:
        deliverables: fleettrack/app.yaml 
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        version: ${{ github.sha }}
        promote: true