name: Build, Test & SonarCloud Analysis

on:
  push:
    branches: [ "code" ]
  pull_request:
    branches: [ "code" ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Chrome and ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          # Assumindo que o requirements.txt está na raiz
          pip install -r requirements.txt
          
      - name: Run Tests and Generate Coverage
        env:
          SECRET_KEY: "dummy-key-for-ci"
          DEBUG: "False"
        run: |
          # Assumindo que manage.py está na raiz
          coverage run manage.py test
          coverage xml -o coverage-report.xml
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=fleettrack-1
            -Dsonar.projectKey=FleetTrack
            -Dsonar.sources=accounts/,dashboard/,fleettrack/
            -Dsonar.python.coverage.reportPaths=coverage-report.xml
            -Dsonar.python.version=3.12